spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/storm?useSSL=false
    username: storm
    password: storm
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
#      prefix: /WEB-INF/jsp/
      prefix: /jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
    enabled: false

server:
  port: 8888
  servlet:
    context-path: /map




